### ISSUE TITLE
Change old syntax to ES 6

### ISSUE THREAD

**Issue by Daniel-Singer** [Daniel-Singer/microDB#2]
The javascript syntax i used should be changed to meet ES6 standards

**Comment by hasheemismath** [comment]
Can I help you solve this issue?
@Daniel-Singer

**Comment by Daniel-Singer** [comment]
Thanks for your interest @hasheemismath . I would be happy if you can solve this issue.

**Comment by hasheemismath** [comment]
@Daniel-Singer Done.
Please check it out here.
https://github.com/Daniel-Singer/microDB/pull/3

**Comment by Daniel-Singer** [comment]
Thank you @hasheemismath!
